version: "3.9"
services:
  command-service:
    build: ./command-service
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
      - mongodb
  command-executor:
    build: ./command-executor
    depends_on:
      - rabbitmq
  statistics-service:
    build: ./statistic-service
    ports:
    - "8082:8080"
    depends_on:
      - redis
      - rabbitmq
  redis:
    image: "redis:latest"
  rabbitmq:
    image: "rabbitmq:latest"
  mongodb:
    image: "mongo:latest"
